# Generated by Django 4.0.10 on 2023-02-25 20:46

import core.wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(db_index=True, default=core.wallet.models.generate_wallet_id, editable=False, max_length=15, verbose_name='Wallet ID'),
        ),
    ]
