# Generated by Django 4.0.10 on 2023-02-24 23:13

import core.event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(db_index=True, default=core.event.models.generate_event_id, editable=False, max_length=15, verbose_name='Event UUID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('single', 'Single'), ('recurring', 'Recurring')], default='single', max_length=10, verbose_name='Event Type'),
        ),
    ]
