# Generated by Django 4.0.10 on 2023-02-25 20:46

import core.order.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_alter_event_event_id_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('order_id', models.CharField(db_index=True, default=core.order.models.generate_order_id, max_length=25)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=25, verbose_name='Order Status')),
                ('paystack_payment_reference', models.CharField(max_length=100, verbose_name='Paystack Ref No.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(default='Deleted Ticket', on_delete=django.db.models.deletion.SET_DEFAULT, to='event.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_id', models.CharField(db_index=True, default=core.order.models.generate_sold_ticket_id, max_length=25)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='events/ticket/', verbose_name='Ticket QR Code')),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('checkin_status', models.CharField(choices=[('new', 'New'), ('in', 'In'), ('out', 'Out')], default='new', max_length=5, verbose_name='Check-in Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_ticket', to='order.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_ticket', to='event.ticket')),
            ],
            options={
                'verbose_name': 'Purchased Ticket',
                'verbose_name_plural': 'Purchased Tickets',
                'ordering': ['-purchased_date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='selected_ticket',
            field=models.ManyToManyField(to='order.ticketorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
